### ISSUE TITLE
Citing flamedisx

### ISSUE THREAD

**Issue by mayou36** [FlamTeam/flamedisx#42]
Is there a way to cite flamedisx currently?

If not, I would propose you to use [zenodo](https://zenodo.org/), login with a github account and activate the automatic pull on releases. This provides a citable DOI.

Let me know if you have questions/problems with it

On the long-term, in case you don't have any plans for a paper, I would recommend to create a [JOSS paper](https://github.com/openjournals/joss), which is short, simple but a full paper. Or of course go for a "real", bigger paper in case you want to. Just better JOSS then Zenodo then nothing ;)

**Comment by pelssers** [comment]
Hi Jonas,
Currently there is no way to cite flamedisx, but Zenodo is exactly what we are planning on using (and have used before on other projects). Since other people like yourself are interested in flamedisx we should do this soon.

**Comment by pelssers** [comment]
We are now on Zenodo from version 0.2.2 onwards. You can find us here:
https://zenodo.org/record/3524865
I've also added the DOI badge to the README page.
Closing.
