### ISSUE TITLE
More flexible event padding

### ISSUE THREAD

**Issue by pelssers** [FlamTeam/flamedisx#45]
As encountered in #43 our event padding code only works when `n_events * 2 >= batch_size`. In practise we don't run into this because we set the batch size appropriately. However, this requirement can be removed by padding with the same event repeatedly. Additionally we could pad with some special placeholder event as long as it doesn't cause issues in the differential rate computation.

**Comment by pelssers** [comment]
Actually, we do run into this when simulating with small rate multipliers. The case for zero events is fixed in #46 but this still limits us to using `batch_size=2` if there is a chance we only simulate one event.

**Comment by pelssers** [comment]
Event padding on single event data is implemented in #54

**Comment by pelssers** [comment]
Event padding is now flexible, fixing this issue. I don't think we'll want to implement different batch sizes for different sources in the likelihood, but could open a new 'enhancement' issue for this. Closing.

**Comment by JelleAalbers** [comment]
I guess we'll want to support the 0-event case eventually as well; it might come up during testing with toy MCs. But for this we can just bypass differential_rate altogether, we don't need to have an 'all padding' batch that is then discarded.

**Comment by pelssers** [comment]
The 0-event case is already supported regarding the simulator in #46, I don't think we need to support `set_data` with 0 events since that is clearly not what `set_data` is for.
I did see an assert in `source.py` that still needs to be removed btw.

**Comment by JelleAalbers** [comment]
OK, good that the simulator already supports this. Observing no events is a legitimate experimental outcome, if set_data doesn't support this we would have to crash when this ever happens in a toy MC. Or maybe we could catch this case in LogLikelihood so the source is never involved.
