### ISSUE TITLE
Tutorial output?

### ISSUE THREAD

**Issue by JelleAalbers** [FlamTeam/flamedisx#49]
It would be nice to also include the output of the tutorial, since this our primary documentation at the moment. The output is currently 1 MB however, and we'll have to regenerate it often, so it will likely bloat the repo. Still, it might be worth it. Ideally we'd have something like straxen does: https://straxen.readthedocs.io/en/latest/tutorials/strax_demo.html, have a readthedocs but render the notebook as markdown. Perhaps we can even:
  * have readthedocs run the notebook for us during the build?
  * have a separate notebooks repo that is autoupdated?

**Comment by pelssers** [comment]
Thanks for adding the tutorial output to the notebook @JelleAalbers .
I've now moved the notebooks folder to the 'flamedisx-notebooks' repository.
