### ISSUE TITLE
Old data sticks around in autograph underworld after Likelihood.set_data

### ISSUE THREAD

**Issue by JelleAalbers** [FlamTeam/flamedisx#53]
When changing datasets with Likelihood.set_data (introduced in #24), autographed functions from tensorflow will continue to refer to the old dataset. This is most visible when you set a dataset with a larger number of batches: then likelihood evaluation with autograph=False works, but with autograph=True it crashes due to an index out of bounds error that can be traced back to here https://github.com/FlamTeam/flamedisx/blob/592562d4654cf77d69d55b91b145a2f4bb36f02d/flamedisx/inference.py#L351

There is actually a comment here https://github.com/FlamTeam/flamedisx/blob/592562d4654cf77d69d55b91b145a2f4bb36f02d/flamedisx/inference.py#L169 that says a retrace is needed (but not done) if the number of batches or padding changes -- which would be always, unless the number of events is exactly equal. In fact, even in that case, a retrace is needed (but not done) with the current implementation.

Likelihood, unlike Source, does not pass the data tensors as arguments to the traced functions. Instead, we get the data tensor from the state of the source (Source.data_tensor). Tensorflow's autograph references the tensor under Source.data_tensor at the moment of tracing, and does not trace the dynamic access to the python attribute of Source.data_tensor.

We should access Source.data_tensor in the python layer, and pass it as an argument to the tensorflow layer, along (I guess) with other needed info such as the amount of padding.

For the moment just not using Likelihood.set_data, or being religious about autograph=False if you do, are the only workarounds I can think of.

**Comment by pelssers** [comment]
Interesting, what happens when you turn off autograph for `LogLikelihood._log_likelihood`, but keep it on for `Source.differential_rate`. My guess is that is works correctly that way. Since we get the main performance benefit from the tracing of `differential_rate` just turning off the outer `log_likelihood` tracing might be an easy fix until we rewrite `set_data` to trigger the retrace.

**Comment by pelssers** [comment]
Implemented in #55 retracing the likelihood is now done after each call to `LogLikelihood.set_data` so no old data sticks around any more. This solves the bug, but performance has to be evaluated. As stated above, we could implement `_log_likelihood` similar to `Source.differential_rate`.
