### ISSUE TITLE
fix_truth argument of simulate modifies dictionary in-place, confusing?

### ISSUE THREAD

**Issue by JelleAalbers** [FlamTeam/flamedisx#86]
For example, drift time gets added if you only provide z. The surprising bit isn't that the drift time gets added (it should, flamedisx needs it) but that it appears in the original dictionary the user passed in. Generally functions that return something are expected to leave their arguments unchanged.

We could add the modified fix_truth to the return value, but then the return of simulate would change once you specify fix_truth. We could also just keep the current behaviour.

**Comment by pelssers** [comment]
Right, that is confusing, what about simply copying the dictionary before validating it (which adds any missing keys such as drift time)?
https://github.com/FlamTeam/flamedisx/blob/5e8c940c206d720bfc64e39bd70e5588a8a18fa1/flamedisx/source.py#L456

**Comment by pelssers** [comment]
I've added my proposed solution to #87
